spring:
  datasource:
    url: jdbc:mysql://192.168.59.129:3306/mikeiansky_oauth2?useSSL=false&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.59.129
      port: 6379
      password:
      database: 15
