spring:
  datasource:
    url: jdbc:mysql://172.16.2.232:3306/mikeiansky_oauth2?useSSL=false&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
