logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: INFO

server:
  port: 8001

spring:
  application:
    name: mikeiansky-oauth2-client
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: spring
            client-id: login-client
            client-secret: openid-connect
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8001/login/oauth2/code/login-client
            scope: openid,profile
            client-name: Spring
        provider:
          spring:
            authorization-uri: http://localhost:9001/oauth2/authorize
            token-uri: http://localhost:9001/oauth2/token
            jwk-set-uri: http://localhost:9001/oauth2/jwks