logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: INFO

server:
  port: 8001

spring:
  application:
    name: mikeiansky-oauth2-client
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: spring
            client-id: login-client
            client-secret: openid-connect
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8001/login/oauth2/code/login-client
#            scope: openid,profile
            scope: profile
#            scope: profile
            client-name: Spring
          github:
            client-id: Iv23ligt91aHp5KeZXTl
            client-secret: c89a8030338decab37bcd427f890f30214d87145
            scope: read:user, user:email
            redirect-uri: http://127.0.0.1:8001/login/oauth2/code/github
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
        provider:
          spring:
            authorization-uri: http://localhost:9001/oauth2/authorize
            token-uri: http://localhost:9001/oauth2/token
            jwk-set-uri: http://localhost:9001/oauth2/jwks
            user-info-uri: http://localhost:9001/oauth2/introspect
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
#            user-name-attribute: id