server:
  port: 8002

spring:
  application:
    name: mikeiansky-oauth2-resource-server
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:9001/oauth2/introspect
          client-id: login-client
          client-secret: openid-connect
